name: Actualizar datos de usuarios

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Actualizar datos de usuarios
        run: |
          cp users-repo/users.json path/to/your/login-system/
